In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()

In [4]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [5]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [6]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [8]:
df = pd.DataFrame(digits.data, columns=digits.feature_names)

In [9]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [10]:
df['target'] = digits.target
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [13]:
#seperating the dataframe into x and y

In [14]:
x = df.drop(['target'], axis='columns')
x

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        5.0        0.0   
3           0.0        0.0        0.0        8.0  ...        9.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        4.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        1.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        2.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        8.0        0.0   

      pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0           0.0        0.0        6.0       13.0       10.0        0.0   
1           0.0        0.0        0.0       11.0       16.0       10.0   
2           0.0        0.0        0.0        3.0       11.0       16.0   
3           0.0        0.0        7.0       13.0       13.0        9.0   
4           0.0        0.0        0.0        2.0       16.0        4.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        2.0       14.0       15.0        9.0   
1793        0.0        0.0        6.0       16.0       14.0        6.0   
1794        0.0        0.0        2.0        9.0       13.0        6.0   
1795        0.0        0.0        5.0       12.0       16.0       12.0   
1796        0.0        1.0        8.0       12.0       14.0       12.0   

      pixel_7_6  pixel_7_7  
0           0.0        0.0  
1           0.0        0.0  
2           9.0        0.0  
3           0.0        0.0  
4           0.0        0.0  
...         ...        ...  
1792        0.0        0.0  
1793        0.0        0.0  
1794        0.0        0.0  
1795        0.0        0.0  
1796        1.0        0.0  

[1797 rows x 64 columns]

In [15]:
y = df.target
y

0       0
1       1
2       2
3       3
4       4
       ..
1792    9
1793    0
1794    8
1795    9
1796    8
Name: target, Length: 1797, dtype: int32

In [16]:
#model selection train and test
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [19]:
#training the model

In [20]:
from sklearn.svm import SVC

In [21]:
#using the default rbf kernel
rbf_clf = SVC(kernel='rbf')

In [22]:
rbf_clf.fit(x_train, y_train)

SVC()

In [24]:
y_pred_test = rbf_clf.predict(x_test)
print(y_pred_test)

[5 5 6 4 1 7 6 1 5 7 2 0 0 7 1 9 8 0 1 6 7 6 7 8 9 1 3 4 1 8 2 9 3 6 7 2 9
 9 0 2 3 0 4 9 6 9 5 9 9 1 6 8 0 7 2 0 8 9 0 7 3 8 2 5 0 8 8 8 3 8 2 5 5 8
 3 0 1 2 9 4 1 1 1 1 9 7 0 4 8 7 4 7 6 7 1 6 9 4 0 5 5 3 0 2 4 3 5 4 9 3 1
 0 1 3 5 5 7 3 0 4 5 7 4 3 1 3 7 2 4 1 4 4 0 2 7 1 8 0 4 4 7 7 4 3 5 6 7 5
 0 5 4 5 0 9 5 1 0 5 4 6 6 0 9 5 3 0 0 1 7 3 7 1 9 1 1 2 0 8 3 8 0 5 6 7 5
 4 4 0 4 0 4 0 1 2 7 8 5 0 7 7 9 4 5 1 4 2 3 1 0 4 5 1 3 8 8 4 3 2 6 1 0 6
 0 2 6 9 7 2 8 6 3 6 9 2 6 9 3 0 6 2 8 5 0 2 2 7 7 9 7 8 6 1 7 1 0 8 9 8 2
 5 6 7 1 0 0 2 0 8 1 8 8 0 4 7 8 6 7 2 4 5 5 4 0 3 4 4 6 9 4 9 9 3 9 9 9 8
 9 9 2 7 4 3 7 3 8 3 3 0 9 6 2 9 5 6 1 9 5 1 3 4 8 4 3 3 6 2 4 6 6 4 9 7 2
 7 2 8 4 4 0 5 4 3 9 7 5 4 0 3 9 3 6 8 6 2 2 5 3 2 2 1 6 4 2 3 9 0 3 7 1 2
 9 3 1 0 2 6 4 0 0 4 0 9 9 2 7 5 6 0 0 8 3 0 8 7 2 1 7 3 8 7 9 6 7 6 2 8 1
 4 7 5 9 3 1 5 8 6 5 6 3 8 5 8 2 0 8 0 2 2 9 3 9 9 2 2 9 9 7 4 8 7 1 5 3 4
 9 1 1 8 9 9 7 8 5 5 2 6 1 9 1 2 8 6 5 8 3 5 7 6 3 7 4 5 0 9 5 2 6 3 3 3 2
 9 6 5 2 6 1 1 2 8 4 6 5 

In [25]:
rbf_clf.score(x_train, y_train)

0.9968178202068417

In [26]:
rbf_clf.score(x_test, y_test)

0.9814814814814815

In [27]:
#linear kernel

In [ ]:
linear_clf = SVC()
clf.fi