In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
print(np.arrange(10))

AttributeError: module 'numpy' has no attribute 'arrange'

In [4]:
print(np.arange(10))    #prints all elements from 0 to 9

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#numpy is memory efficient takes micro second provides fast numerical operations
#numpy is more efficient than python lists

In [6]:
#1D arrays

a1 = np.array([2,3,4,5,6])
a1

array([2, 3, 4, 5, 6])

In [7]:
a1.ndim   #shows the dimension of the array

1

In [8]:
len(a)   #finds the length of the array

4

In [11]:
a1.shape   #finds the number of rows and columns

(5,)

In [12]:
#2D array

b = np.array([[1,2,3], [2,3,4], [4,5,6]])
b

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [13]:
print(b)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [14]:
b.ndim

2

In [15]:
b.shape

(3, 3)

In [17]:
#functions for creating array

c = np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
d = np.arange(1,10,2)  #start end diff
print(d)  #prints elements from 1 to 10 with difference 2

[1 3 5 7 9]


In [22]:
#linspace

e = np.linspace(0,1,6)  #start   end   no. of points
print(e)   #prints 6 elements between 0 and 1 with a uniform difference of 0.2

[0.  0.2 0.4 0.6 0.8 1. ]


In [24]:
#common arrays
#array of ones

f = np.ones((3,3))
print(f)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
#array of zeros
g = np.zeros((2,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]]


In [28]:
#identity matrix of size n

i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
#diagonal matrix

di = np.diag([1,2,3,4])
print(di)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [31]:
np.diag(di)   #extract diagonal elements

array([1, 2, 3, 4])

In [32]:
#create array of random numbers

j = np.random.rand(4)
print(j)

[0.47028249 0.40466327 0.7534363  0.97767343]


In [34]:
#Basic data types

arr = np.arange(10)
print(arr.dtype)

int32


In [35]:
fl = np.arange(6, dtype='float64')
print(fl)

[0. 1. 2. 3. 4. 5.]


In [36]:
comp = np.array([1+2j, 2+5j])  #complex datatype
print(comp.dtype)

complex128


In [37]:
boo = np.array([True, True, False, False, False, True])
print(boo.dtype)

bool


In [38]:
#Indexing

a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [40]:
print(a[2, 2])

3


In [41]:
#assign

a[2,1] = 5
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 5 3 0]
 [0 0 0 4]]


In [42]:
#Slicing

b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
b[1:8:2]   #start  end  diff

array([1, 3, 5, 7])

In [44]:
b[5:] = 10   #from 5th index it assigns every value with 10 till last index
b

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [45]:
c = np.arange(5)
b[5:] = c[::-1]  #assigns all the reverse values of c from 5th index of b
b

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])