In [2]:
#fancy indexing
#using boolean mask
import numpy as np
a = np.random.randint(0,20,15)        #generates 15 random numbers from 0 to 20 (start  end  no.we want)
a

array([ 2,  5, 19, 19, 16, 16, 13, 13, 10, 10,  7, 10, 13,  6,  3])

In [3]:
mask = (a%2 == 0)

In [5]:
extract_from_a = a[mask]
extract_from_a

array([ 2, 16, 16, 10, 10, 10,  6])

In [6]:
a[mask] = -1;
a

array([-1,  5, 19, 19, -1, -1, 13, 13, -1, -1,  7, -1, 13, -1,  3])

In [7]:
#indexing with array of integers

b = np.arange(0,100,10)
b

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
b[[2,3,2,4,2]]     #creates an array of the indexes passed

array([20, 30, 20, 40, 20])

In [11]:
#changing values at multiple indexes with a same value

b[[9,7]] = -200
b

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])