In [1]:
#Copies and Views
#IMP topic

import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = a[::2]   #the values are copied from a to b by leaving a diff of 2
b

array([0, 2, 4, 6, 8])

In [4]:
np.shares_memory(a,b)

True

In [5]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [6]:
a      #here changing the b will also reflected in a as the same memory is shared

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [7]:
#To avoid this we can use copy
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [9]:
np.shares_memory(a,c)     #here the memory will not be shared

False

In [11]:
c[0] = 12
c

array([12,  2,  4,  6,  8])

In [12]:
a    #here it is not reflected in a as we used copy , which creates 2 different copies and don't use the same memory


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
d = np.arange(5)
d

array([0, 1, 2, 3, 4])

In [14]:
e = d
e

array([0, 1, 2, 3, 4])

In [15]:
np.shares_memory(d,e)

True